# Generated by Django 5.2.9 on 2026-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
